

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/local
    username: root
    password: root

